# This cloudbuild file is used by GitHub integration and dev trigger.
steps:
# 0. Lint the library and run tests in docker
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '${_LIBRARY_NAME}', '.', '--cache-from', 'eu.gcr.io/$PROJECT_ID/${_LIBRARY_NAME}']
substitutions:
  _LIBRARY_NAME: mockserver-client-go
